{% set name = "giturlparse" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/giturlparse-{{ version }}.tar.gz
  sha256: c0fff7c21acc435491b1779566e038757a205c1ffdcb47e4f81ea52ad8c3859a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=40.6.0
    - pip
  run:
    - python >=3.8

test:
  imports:
    - giturlparse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nephila/giturlparse
  summary: A Git URL parsing module (supports parsing and rewriting)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
