schema_version: 1

context:
  name: giturlparse
  version: 0.14.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/giturlparse-${{ version }}.tar.gz
  sha256: 0a13208cb3f60e067ee3d09d28e01f9c936065986004fa2d5cd6db7758e9f6e6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=40.6.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - giturlparse
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A Git URL parsing module (supports parsing and rewriting)
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/nephila/giturlparse

extra:
  recipe-maintainers:
    - thewchan
